project:
  type: book
  output-dir: _book

book:
  title: "Introducci칩n a la probabilidad para en an치lisis de datos"
  author: "Amphibian/Anuran community"
  date: "2/8/2023"
  reader-mode: true
  
  page-footer:
    left: |
      Introducci칩n a la probabilidad para en an치lisis de datos.
    right: |
     Este libro se ha creado con  <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://github.com/RicUIB/Enlaces
  repo-url: https://github.com/RicUIB/Enlaces
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - 0.qmd
    - 1.qmd
    - 2.qmd
    - 3.qmd
    - 4.qmd
    - 5.qmd
    - 6.qmd
    - 7.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



